import CryptoKit
import CoreFoundation
import Foundation

/// Absolute dates generated by the shared Flutter timetable planner.
/// This store is independent of the display cache and contains no credentials.
struct NativeCourseReminder: Codable, Equatable {
  let id: String
  let title: String
  let location: String
  let teacher: String
  let showAt: Date
  let startsAt: Date
  let endsAt: Date
  let dismissAt: Date

  init?(json: [String: Any]) {
    func instant(_ key: String) -> Date? {
      guard let number = json[key] as? NSNumber, CFGetTypeID(number) != CFBooleanGetTypeID(),
            number.doubleValue.isFinite else { return nil }
      return Date(timeIntervalSince1970: number.doubleValue / 1000)
    }
    guard let id = json["id"] as? String, !id.isEmpty, id.utf8.count <= 2048,
          let title = json["title"] as? String, !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
          let show = instant("showAt"), let start = instant("startsAt"),
          let end = instant("endsAt"), let dismiss = instant("dismissAt"),
          abs(start.timeIntervalSince(show) - 900) < 0.01,
          abs(dismiss.timeIntervalSince(start) - 60) < 0.01,
          end > start, end.timeIntervalSince(start) <= 12 * 3600 else { return nil }
    self.id = id
    self.title = String(title.prefix(80))
    location = String((json["location"] as? String ?? "").prefix(80))
    teacher = String((json["teacher"] as? String ?? "").prefix(40))
    showAt = show; startsAt = start; endsAt = end; dismissAt = dismiss
  }

  static func digest(_ value: String) -> String {
    SHA256.hash(data: Data(value.utf8)).map { String(format: "%02x", $0) }.joined()
  }

  func identifier(scope: String) -> String {
    "xinli.course." + Self.digest(scope + "\n" + id)
  }

  /// Finite one-off queue; never turn an obsolete timetable into weekly alarms.
  static func upcoming(_ courses: [Self], now: Date) -> [Self] {
    var seen = Set<String>()
    return courses.filter {
      $0.dismissAt > now && $0.startsAt < now.addingTimeInterval(7 * 86400) && seen.insert($0.id).inserted
    }.sorted {
      $0.startsAt == $1.startsAt ? $0.id < $1.id : $0.startsAt < $1.startsAt
    }.prefix(48).map { $0 }
  }
}
